spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  #minio配置 https://blog.csdn.net/qq_36856047/article/details/124154748
  minio:
    endpoint: http://101.37.117.226:9090
    access-key: 7v3qUvGaLweXRbw4
    secret-key: v2ZHnvUAokuztsr3HaO0f1cpC0dkIzLW
    url: http://101.37.117.226:22122
    bucket-name: wdhcr
  thymeleaf:
    cache: false
server:
  port: 8081